//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdPen { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> SummPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
