//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeClient
    {
        public TypeClient()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
